import { useState } from 'react'
import { Pencil, Route } from 'lucide-react'
import { useLocalRoute } from '../hooks/useEnrollment'
import { useModules } from '../hooks/useFormation'
import { useAddModuleToStudyCycle, useCreateStudyCycle, useStudyCycles, useStudyCycleModules, useUpdateStudyCycle, useUpdateStudyCycleModuleStatus } from '../hooks/useStudyCycles'

export function StudyCycleSettings() {
  const { data: route } = useLocalRoute(); const { data: modules = [] } = useModules(); const { data: cycles = [] } = useStudyCycles(); const createCycle = useCreateStudyCycle(); const updateCycle = useUpdateStudyCycle(); const updateModule = useUpdateStudyCycleModuleStatus(); const addModuleMutation = useAddModuleToStudyCycle()
  const [selectedCycleId, setSelectedCycleId] = useState<string | null>(null); const [name, setName] = useState(''); const [startsOn, setStartsOn] = useState(''); const [editingId, setEditingId] = useState<string | null>(null)
  const selectedCycle = cycles.find((cycle) => cycle.id === selectedCycleId) ?? cycles[0]; const { data: cycleModules = [] } = useStudyCycleModules(selectedCycle?.id ?? null)
  async function create(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) return; const cycle = await createCycle.mutateAsync({ route_id: route?.id ?? null, name: name.trim(), starts_on: startsOn || null }); setSelectedCycleId(cycle.id); setName(''); setStartsOn('') }
  async function saveEdit(event: React.FormEvent) { event.preventDefault(); if (!editingId || !name.trim()) return; await updateCycle.mutateAsync({ id: editingId, name: name.trim(), starts_on: startsOn || null }); setEditingId(null); setName(''); setStartsOn('') }
  async function addModule(moduleId: string) { if (!selectedCycle) return; const orderIndex = modules.find((module) => module.id === moduleId)?.order_index ?? 0; await addModuleMutation.mutateAsync({ studyCycleId: selectedCycle.id, moduleId, orderIndex }) }
  return <section className="rounded-2xl border bg-card p-5"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Route className="size-5" /></span><div><h2 className="font-semibold">Ciclos de estudio</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Crea el ciclo general y define qué módulo está pendiente, activo o terminado.</p></div></div>
    <form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-[1fr_180px_auto]"><input value={name} onChange={(event) => setName(event.target.value)} className="h-10 rounded-lg border bg-background px-3 text-sm" placeholder="Ejemplo: Ciclo 2026 - 2027" required /><input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} className="h-10 rounded-lg border bg-background px-3 text-sm" aria-label="Inicio del ciclo" /><button type="submit" disabled={createCycle.isPending} className="rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground">Crear ciclo</button></form>
    <div className="mt-5 grid gap-5 lg:grid-cols-[280px_1fr]"><div className="space-y-2">{cycles.map((cycle) => editingId === cycle.id ? <form key={cycle.id} onSubmit={saveEdit} className="space-y-2 rounded-lg border p-3"><input value={name} onChange={(event) => setName(event.target.value)} className="h-9 w-full rounded border bg-background px-2 text-sm" required /><input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} className="h-9 w-full rounded border bg-background px-2 text-sm" /><div className="flex gap-2"><button className="rounded bg-primary px-2 py-1 text-xs text-primary-foreground">Guardar</button><button type="button" onClick={() => setEditingId(null)} className="rounded border px-2 py-1 text-xs">Cancelar</button></div></form> : <button type="button" key={cycle.id} onClick={() => setSelectedCycleId(cycle.id)} className={`flex w-full items-center justify-between rounded-lg border px-3 py-3 text-left text-sm ${selectedCycle?.id === cycle.id ? 'border-primary bg-primary/5' : ''}`}><span><span className="block font-medium">{cycle.name}</span><span className="text-xs text-muted-foreground">{cycle.status === 'active' ? 'Activo' : cycle.status}</span></span><Pencil className="size-4 text-muted-foreground" onClick={(event) => { event.stopPropagation(); setEditingId(cycle.id); setName(cycle.name); setStartsOn(cycle.starts_on ?? '') }} /></button>)}</div><div><h3 className="font-semibold">Módulos del ciclo{selectedCycle ? ` · ${selectedCycle.name}` : ''}</h3>{!selectedCycle ? <p className="mt-2 text-sm text-muted-foreground">Crea o selecciona un ciclo para administrar sus módulos.</p> : <div className="mt-3 space-y-2">{modules.filter((module) => module.is_active).map((module) => { const item = cycleModules.find((entry: any) => entry.module_id === module.id); return <div key={module.id} className="flex items-center justify-between rounded-lg border px-3 py-2"><span className="text-sm font-medium">{module.name}</span>{item ? <select value={item.status} onChange={(event) => updateModule.mutate({ studyCycleId: selectedCycle.id, moduleId: module.id, status: event.target.value as 'pending' | 'active' | 'completed' | 'paused' })} className="h-8 rounded border bg-background px-2 text-xs"><option value="pending">Pendiente</option><option value="active">Activo</option><option value="completed">Terminado</option><option value="paused">Pausado</option></select> : <button type="button" onClick={() => void addModule(module.id)} className="rounded border px-2 py-1 text-xs">Agregar</button>}</div>})}</div>}</div></div>
  </section>
}
